/** 设计系统 — Vercel 暗色主题 */
import type { ThemeConfig } from "antd";

export const COLORS = {
  bg: { page: "#000000", card: "#0d0d0d", elevated: "#1a1a1a", overlay: "#222222" },
  border: { default: "#1e1e1e", hover: "#333333" },
  text: { primary: "#ededed", secondary: "#a1a1aa", tertiary: "#52525b" },
  accent: { blue: "#3b82f6", green: "#22c55e", red: "#ef4444", orange: "#f59e0b", purple: "#8b5cf6" },
} as const;

export const SPACING = { xs: 4, sm: 8, md: 12, lg: 16, xl: 24, xxl: 32, xxxl: 48 } as const;

export const themeConfig: ThemeConfig = {
  algorithm: undefined, // 完全自定义，不用 Ant Design 默认算法
  token: {
    colorPrimary: COLORS.accent.blue,
    colorBgContainer: COLORS.bg.card,
    colorBgElevated: COLORS.bg.elevated,
    colorBgLayout: COLORS.bg.page,
    colorBorder: COLORS.border.default,
    colorBorderSecondary: COLORS.border.default,
    colorText: COLORS.text.primary,
    colorTextSecondary: COLORS.text.secondary,
    colorTextTertiary: COLORS.text.tertiary,
    colorBgTextHover: COLORS.bg.elevated,
    colorBgMask: "rgba(0,0,0,0.6)",
    colorSuccess: COLORS.accent.green,
    colorWarning: COLORS.accent.orange,
    colorError: COLORS.accent.red,
    colorInfo: COLORS.accent.blue,
    borderRadius: 8,
    borderRadiusLG: 12,
    borderRadiusSM: 4,
    fontFamily: `Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif`,
    fontSize: 14,
    fontSizeHeading1: 30,
    fontSizeHeading2: 24,
    fontSizeHeading3: 20,
    fontSizeHeading4: 16,
    fontSizeHeading5: 14,
    lineHeight: 1.6,
    lineHeightHeading1: 1.3,
    lineHeightHeading2: 1.35,
    lineHeightHeading3: 1.4,
    margin: SPACING.lg,
    padding: SPACING.lg,
    paddingXS: SPACING.sm,
    paddingSM: SPACING.md,
    paddingLG: SPACING.xl,
    marginXS: SPACING.sm,
    marginSM: SPACING.md,
    marginLG: SPACING.xl,
    controlHeight: 36,
    controlHeightSM: 28,
    controlHeightLG: 44,
  },
  components: {
    Layout: {
      headerBg: COLORS.bg.page,
      headerPadding: `0 ${SPACING.xxl}px`,
      bodyBg: COLORS.bg.page,
      siderBg: COLORS.bg.page,
    },
    Card: {
      colorBgContainer: COLORS.bg.card,
      colorBorderSecondary: COLORS.border.default,
      paddingLG: SPACING.lg,
      borderRadiusLG: 8,
    },
    Table: {
      colorBgContainer: "transparent",
      headerBg: "transparent",
      headerColor: COLORS.text.secondary,
      headerBorderRadius: 0,
      rowHoverBg: COLORS.bg.elevated,
      borderColor: COLORS.border.default,
      padding: 12,
      fontSize: 13,
      lineHeight: 1.5,
    },
    Menu: {
      itemBg: "transparent",
      itemColor: COLORS.text.secondary,
      itemHoverColor: COLORS.text.primary,
      itemHoverBg: "transparent",
      itemSelectedColor: COLORS.text.primary,
      itemSelectedBg: "transparent",
      horizontalItemSelectedColor: COLORS.accent.blue,
      horizontalItemHoverColor: COLORS.text.primary,
    },
    Input: {
      colorBgContainer: COLORS.bg.elevated,
      colorBorder: COLORS.border.default,
      activeBorderColor: COLORS.accent.blue,
      hoverBorderColor: COLORS.border.hover,
      colorText: COLORS.text.primary,
      colorTextPlaceholder: COLORS.text.tertiary,
      addonBg: COLORS.bg.elevated,
    },
    Select: {
      colorBgContainer: COLORS.bg.elevated,
      colorBorder: COLORS.border.default,
      activeBorderColor: COLORS.accent.blue,
      hoverBorderColor: COLORS.border.hover,
      colorText: COLORS.text.primary,
      selectorBg: COLORS.bg.elevated,
      multipleItemBg: COLORS.bg.card,
    },
    Button: {
      colorBgContainer: COLORS.bg.elevated,
      colorBorder: COLORS.border.default,
      colorText: COLORS.text.secondary,
      primaryColor: "#ffffff",
      colorPrimary: COLORS.accent.blue,
      colorPrimaryHover: "#60a5fa",
      colorPrimaryActive: "#2563eb",
      borderColorDisabled: COLORS.border.default,
    },
    Tag: {
      colorBgContainer: COLORS.bg.elevated,
      colorText: COLORS.text.secondary,
    },
    Modal: {
      colorBgContainer: COLORS.bg.card,
      colorBgElevated: COLORS.bg.overlay,
      headerBg: COLORS.bg.card,
      contentBg: COLORS.bg.card,
      footerBg: COLORS.bg.card,
    },
    Tabs: {
      colorBgContainer: "transparent",
      inkBarColor: COLORS.accent.blue,
      itemColor: COLORS.text.secondary,
      itemHoverColor: COLORS.text.primary,
      itemSelectedColor: COLORS.accent.blue,
    },
    Statistic: {
      contentFontSize: 28,
      titleFontSize: 13,
    },
    Spin: {
      colorPrimary: COLORS.accent.blue,
    },
    Pagination: {
      colorBgContainer: "transparent",
      colorBorder: COLORS.border.default,
      itemActiveBg: COLORS.bg.elevated,
    },
    Empty: {
      colorText: COLORS.text.tertiary,
      colorTextDescription: COLORS.text.tertiary,
    },
    Tooltip: {
      colorBgContainer: COLORS.bg.overlay,
      colorText: COLORS.text.primary,
    },
  },
};
